[package]
name = "pdc"
version = "0.1.0"
authors = ["Fabricio Aguiar <fabricio.aguiar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10.4", features = ["blocking"] }
select = "0.4.3"
tempfile = "3.1.0"
zip = "0.5.5"