[package]
name = "pdc"
version = "0.1.0"
authors = ["Fabricio Aguiar <fabricio.aguiar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.4"
tokio = { version = "0.2", features = ["macros"] }